### ISSUE TITLE
Clarification of redstone signal for heat source

### ISSUE THREAD

**Issue by Ozzymud** [TheLimePixel/Modern-Skyblock-Classic#13]
I had a very hard time trying to get my 1st iron. In the guide it shows a torch as a heat source, this appears to be disabled which is all well and good. I started by using the wooden heat source as I had successfully used for the crucible. I could not get the condenser to convert the liquid iron no matter how long I waited. The condenser appeared to be working as it had "bubbles" in the iron liquid. The only reference I could find was a german youtuber doing a lets play, he had the exact same issue in episode 5 near the end: https://youtu.be/kVofY8H-_xc?t=1038 

Just today he posted a new video where he had figured it out, the lever on the heat source was sending it's signal to the condenser as well turning it off... the solution was to place a block beside the heat source and attach the lever to it...

This somehow needs to be clarified in the guide I personally think.

Not working:
![2019-06-11_14 32 02](https://user-images.githubusercontent.com/6426344/59308391-ccf18580-8c55-11e9-9c63-21ac681da685.png)

Working:
![2019-06-11_14 32 12](https://user-images.githubusercontent.com/6426344/59308398-d0850c80-8c55-11e9-8723-b20a228d5a88.png)

**Comment by TheLimePixel** [comment]
The guide already mentions that Condensers and Crystallizers are disabled via redstone signal. The signal transferring to adjacent blocks is a vanilla thing that every should be aware of. I will however add a note for it to the guide.
