### ISSUE TITLE
Changed Title/Issue: Cauldron should clean dirty items when tossed in

### ISSUE THREAD

**Issue by Ozzymud** [TheLimePixel/Modern-Skyblock-Classic#15]
Placed a cauldron (cheated in at this point, finding too many bugs). Filled it with water from a ceramic bucket, tossed in all the dirty resources and stone dust I received from a stack of smooth stone. Result was nothing happening except for the items returning to my inventory as if I had just tossed them on the ground at my feet. Images show dirty lapis sitting in a freshly filled cauldron and my inventory of the other resources I tried. 

![2019-06-12_02 41 05](https://user-images.githubusercontent.com/6426344/59341284-75d2cb80-8cbc-11e9-9557-fec6e534a6e7.png)

![2019-06-12_02 44 05](https://user-images.githubusercontent.com/6426344/59341285-766b6200-8cbc-11e9-8554-d86a640f7345.png)

**Comment by dotsofdarkness** [comment]
you have to right click on the cauldron to wash the gems

**Comment by Ozzymud** [comment]
That would explain that one. Could have swore I remember the original sky resources being able to toss them in... maybe I just confused it with gregtech. That is a method I personally think should be changed. Seems like just another mechanic to make some task more grindy.

**Comment by TheLimePixel** [comment]
I'm gonna say no.
