### ISSUE TITLE
Heat sources listing in JEI; strange entries

### ISSUE THREAD

**Issue by Ozzymud** [TheLimePixel/Modern-Skyblock-Classic#16]
When viewing heat sources, there are 3 listed strangely without an icon; tile.fire (7 heat), 2 tile.lava entries one with 5 heat the other with 3 (assuming source versus flowing?).  

![2019-06-12_02 53 12](https://user-images.githubusercontent.com/6426344/59341876-80419500-8cbd-11e9-8011-977c5b71ab4f.png)

![2019-06-12_02 55 30](https://user-images.githubusercontent.com/6426344/59341898-8f284780-8cbd-11e9-9020-3fc5152a086e.png)

On a semi-related note, the guide where it shows how to build structure shows a vanilla torch as a valid heat source and it appears to not be one as far as JEI or in world testing show.

**Comment by TheLimePixel** [comment]
Lava and Fire can't be displayed as items. It's always been like that.
