### ISSUE TITLE
flying ring recipe doesn't work

### ISSUE THREAD

**Issue by dotsofdarkness** [TheLimePixel/Modern-Skyblock-Classic#7]
this recipe shows in JEI as craftable but doesn't work in a crafting grid
![2019-06-08_20 35 06](https://user-images.githubusercontent.com/41033881/59145854-f380a800-8a2c-11e9-8525-f56ae3bcecbe.png)
![2019-06-08_20 26 56](https://user-images.githubusercontent.com/41033881/59145785-f62ecd80-8a2b-11e9-89db-836ca63c4640.png)
the crafting recipes for the other ways to craft the flying ring work its just the simple one that dosent

**Comment by TheLimePixel** [comment]
Well, that recipe does seem a bit too simple, so I'll just remove it.
